# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FlipsideDatabridgeAPI.Model.ActiveRecord do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"consumer_id",
    :"topic_slug",
    :"retry_count",
    :"partition",
    :"offset"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"consumer_id" => String.t,
    :"topic_slug" => String.t,
    :"retry_count" => float(),
    :"partition" => float(),
    :"offset" => float()
  }
end

defimpl Poison.Decoder, for: FlipsideDatabridgeAPI.Model.ActiveRecord do
  def decode(value, _options) do
    value
  end
end

