# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FlipsideDatabridgeAPI.Model.Metadata do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"unread_records"
  ]

  @type t :: %__MODULE__{
    :"unread_records" => float()
  }
end

defimpl Poison.Decoder, for: FlipsideDatabridgeAPI.Model.Metadata do
  def decode(value, _options) do
    value
  end
end

