# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FlipsideDatabridgeAPI.Model.NewRecord do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :body
  ]

  @type t :: %__MODULE__{
          :body => %{}
        }
end

defimpl Poison.Decoder, for: FlipsideDatabridgeAPI.Model.NewRecord do
  def decode(value, _options) do
    value
  end
end
