# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FlipsideDatabridgeAPI.Model.NewRecordRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :data
  ]

  @type t :: %__MODULE__{
          :data => [ErrorUnknown]
        }
end

defimpl Poison.Decoder, for: FlipsideDatabridgeAPI.Model.NewRecordRequest do
  import FlipsideDatabridgeAPI.Deserializer

  def decode(value, options) do
    value
  end
end
