# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FlipsideDatabridgeAPI.Model.UpdatedRecordState do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"state"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"state" => String.t
  }
end

defimpl Poison.Decoder, for: FlipsideDatabridgeAPI.Model.UpdatedRecordState do
  def decode(value, _options) do
    value
  end
end

